### ISSUE TITLE
Fyers and alice blue are providing free data in realtime, can we implement same using those API

### ISSUE THREAD

**Issue by raviyellani** [ashc0de/options-oi#1]

**Comment by ashok-kollipara** [comment]
Hey,

Yes we can do that in similar manner. The code will need modification to grab and process data from Fyers or AliceBlue.

However there are few things to note :
1. You will need to have an account with the above mentioned brokers to access that data stream/API.
2. Authentication needs to be done.
3. They get the data from NSE only, which the API I am currently utilizing in this repo / code (without any authentication as its public)

One more thing to note is that Open Interest (topic of this repo) barely changes in a span of minute, so higher time frames and delays do provide sufficient reaction times.

Hope this clears your queries
